stages:
  - merge requests
  - build
  - test
  - push
  - deploy

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

merge requests:
  stage: merge requests
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    - echo "Only on merge requests ..."

build:
  stage: build
  script:
    - docker build --tag="$CI_REGISTRY_IMAGE":"$CI_COMMIT_REF_NAME" .

test:
  stage: test
  script:
    - docker-compose run simple_app python manage.py test

push:
  stage: push
  script:
    - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_REF_NAME"

deploy dev:
  stage: deploy
  environment:
    name: dev
  tags:
    - dev
  script:
    - docker-compose pull
    - docker-compose down
    - docker-compose up -d

deploy prod:
  stage: deploy
  when: manual
  environment:
    name: prod
  tags:
    - prod
  script:
    - docker-compose pull
    - docker-compose down
    - docker-compose up -d

